language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

env:
  - MOZ_HEADLESS=1
  - GECKODRIVER_VERSION=0.23.0

addons:
  firefox: latest

before_install:
  - pip install -r requirements.txt

env:
  matrix:
  - DJANGO=2.1.5
  global:
  - DJANGO_SETTINGS_MODULE='mysite.settings'
  - CODECOV_TOKEN="a8e814d9-19c3-48f3-98ea-0ef43961a892"
#the command below will be invoked to install any dependencies - don't
#have any yet so it is commented out
#the command below will manage the testing - set up at present to look at the
script:
  - pytest
