language: python
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
env:
  matrix:
  - DJANGO=2.1.5
  global:
  - DJANGO_SETTINGS_MODULE='mysite.settings'
  - CODECOV_TOKEN="a8e814d9-19c3-48f3-98ea-0ef43961a892"
addons:
  firefox: latest
before_install:
- pip install -r requirements.txt
- wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
script:
- pytest
after_success:
- codecov
deploy:
  provider: heroku
  api_key:
    secure: VkD9073Jt7wMvy8ixtCrg2o+ozeij0dFj3zTDxqtENF1lMA+oucCiMYO7pribrCKyEPWwCTotW0WCljB5d7pqS0MnEVVFfa4INvM9gxCxNny9y+/FgQGVKBO3YxFItVW5ftyNCYfenaqkfWdqA/iZMsKbX2h5B2ISYg/rfVuX5aEEP9jDn1NhNs241YvoOEwCTYPJrUXr8hHKFsqjQ/8jwFF6NUPQg48oPkQFdpx8V8n3qtBtO9n0+bE6JUdtye7RPGe0fVl0T6oL1DJ0ZY/r3ipABDsXZgi5pB8GcYUr1LE9nlNZz04PFucfc7SuNiFUlq6Qybw6ATYKGwfQfF9LlRf7TWkKE/qLVirnFiOug0uZgNbqF+yGOtlDgcvmCOCYdzMp7106K83O+ftyYChHoBAn7BxvbsNxCvSFvV7zj1lnESuUBLrovr63a50GGhRLrFwHVWdosravct8RDo4ZgZvAvNvgeaJqt2HxjArx9ibRJxjQNgUsKtRf+l/mptDXo5QDRA+yvxoDfObKjs8aKIoXvbXyXRQK5NOh4WWoK7nvonMgEkS7GoUOBApYNM9gz1Cp2By5VAOwIr+aAr4rOvNX5gSgLt0h48yhR9rwmA6GEcAeM2WyW8EmTjuX0e9fIPgbCZR3K2wNSYshCqdLnpdPsDFg5PzRhIHZKRbJSc=
  app:
    master: tweet-mood
    heroku: tweet-mood
