language: python
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
env:
  matrix:
  - DJANGO=2.1.5
  global:
  - DJANGO_SETTINGS_MODULE='mysite.settings'
  - CODECOV_TOKEN="a8e814d9-19c3-48f3-98ea-0ef43961a892"
addons:
  firefox: latest
before_install:
- pip install -r requirements.txt
- wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
script:
- pytest
after_success:
- codecov
deploy:
  provider: heroku
  on: heroku
  api_key:
    secure: T7l1/WWhz2XfdPzGkkA/GW0lZWH0LbNk35Nb1C/1/QNydYqqTYDL7b2e/9GpTy9fsCCFZdgboYSOmGlOVg5RWGSdtmp4FqmblbtRqSI7aD3RJ36VvohOdDMgBWvCorpGji/xxh6Ex/X5wBk+jm3Hq2kXSs5se07KPYoYnhpBYTNKEmJB4tIdRhvw+ZCTuGJi6LiRKH9uihGIJ16SSEyqMuf8Ybiq/8ezFFYu+DuTqPfYdaUiux1fwBZe7HyJcrwRiY14ULGbFgohPA/FKZUCM5r/kn3Zy7fjcXi8VCH/78ccThwpi9It8kyEPmBbm1KEdlH4J1M0cW/XaSOseHHcKhoDxc3NI+xwCAvNnBrE/AFbKm9jVUvyqJLUf5spy7ZydPKAZ6EcYA6xb/WGgQ3at5pNNEEaudr10zqHpnSkMiDA4R9qOOhyN0Q0AngROotsDJBQ/BjLVKeXUYptIsupUqWxLHQfuRP6Nkxv91phGDI5cn3GDVpRnvg7133KgiTJAc89DYVmoLnrE/my7Mm61avccuPfdFrt3IPulQV2yTu2+4lais209w1aGcx4VKJLp05hrlksaANHZAvQPYwZ3o/f2ttCMSBrQfNWhTDS/3RA5zqn5MzzpfqVRh+11XHYcGy7DLyQFxwYocOmL7XjSQ9qTEFZB/Wb35qGJKwgw64=
  app: tweet-mood
