language: python
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
env:
  matrix:
  - DJANGO=2.1.5
  - secure: Vh12himfWf/zBIjRq8dqY4GqWeQ8aIv9NrvnlqSeze5agL5J1Xtx1DYyWJGsyCEEzp9TxH064wz+sqB9bgVokI+F8VeFlN9eCVhz612BLgMaXjjL/hK43YCmSzXfWdQ6lh7DfQj+/OZqRX5shSHf48KhduWdvcImKZHnWWZKQaqART6ZmS39eXZ+akY+KjbfcakNHzx+m8yrKj+X3io3jtgIiKCV657OT+1ophKdVMChCyZJcl42J8ANWqMJVl0DMB6yh0t4VZr8yqnT9JRoVo+PBXHUlwmh1oL5YJJHhVYdxXJ3P6X1SjnxeclSsWTgRe+Kj5GJDbhhk6WDDubn7uNLnBoUHQF/xuacBu7YrZdc9SzFcA+FXkdy8pD/M/NLUZ9QPaBXnVsBbCennbizKwUZCaEWRVMcjli2m8sd5zqb+grxF4zmSOQO7JCtBgoks2LTDYKcmOZvV0RVeYYlgt6KTVGWxEpwItmQ8h2PC1ZoeHhjhlWd1fw6nk8u7hTTXgFZI1b9uy5Ht/3P8z0UHXNUFsFcMLlZLiZ9ECDPGxqYnOE0w1t8a+j8WGzQcQaasyrCbgQpJCJX3wGeIcCwD11E0CVztvlpr8te/LNuXiQu+mG1L29sVNVt3f5VJk1x6DpTNnAq6QEEBwvvumv+ZhPoNM0ICMfFeBaxfi5DonM=
  global:
  - DJANGO_SETTINGS_MODULE='mysite.settings'
  - CODECOV_TOKEN="a8e814d9-19c3-48f3-98ea-0ef43961a892"
addons:
  firefox: latest
before_install:
- pip install -r requirements.txt
- wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
script:
- pytest
after_success:
- codecov
